#!/usr/bin/env bash
set -aeo pipefail; [[ $DOKKU_TRACE ]] && set -x
if [ -f "$DOKKU_ROOT/$1/ENV" ]
then
  source $DOKKU_ROOT/$1/ENV
fi

APP="$1"; PORT="$2"

#REVISION=`cat $DOKKU_ROOT/$APP/refs/heads/master`

PARSER='{
        DATA=""
        for(i=3; i<=NF; i++) DATA=DATA" -d "$(i)
        print("echo -----> Acessing "$2"...")
        print("curl -X "$1" "$2DATA)
}'
docker run --rm app/$APP bash -c '[ -f /app/.webhook ] && cat /app/.webhook' | awk "$PARSER" | bash
