#!/usr/bin/env bash
echo 'teste'
set -aeo pipefail; [[ $DOKKU_TRACE ]] && set -x
source /home/dokku/$1/ENV
APP="$1"; PORT="$2"; REVISION=`cat /home/dokku/$APP/refs/heads/master`
docker run --rm app/$APP cat /app/.webhook | awk -f parser.awk | bash
